# Generated by Django 3.2.6 on 2021-08-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remorque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matriculation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matriculation', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('remorque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camionremorque.remorque')),
            ],
        ),
    ]
