# Generated by Django 3.2.6 on 2021-08-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camionremorque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='remorque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camionremorque.remorque'),
        ),
    ]
