# Generated by Django 3.2.6 on 2021-08-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camionremorque', '0002_alter_camion_remorque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='designation',
        ),
    ]
