# Generated by Django 3.2.6 on 2021-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camionremorque', '0003_remove_camion_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
